/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 42
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON_COLON = 1,
  sym_passage_name = 2,
  anon_sym_LBRACK = 3,
  anon_sym_RBRACK = 4,
  aux_sym_tag_list_token1 = 5,
  sym_tag = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  sym_json_metadata = 9,
  aux_sym_text_token1 = 10,
  anon_sym_LT = 11,
  anon_sym_LT_LT = 12,
  anon_sym_GT_GT = 13,
  sym_macro_name = 14,
  anon_sym_EQ = 15,
  anon_sym_COMMA = 16,
  anon_sym_COLON = 17,
  aux_sym_macro_arg_token1 = 18,
  anon_sym_DQUOTE = 19,
  aux_sym_string_token1 = 20,
  anon_sym_SQUOTE = 21,
  aux_sym_string_token2 = 22,
  sym_variable = 23,
  sym_attribute_name = 24,
  sym_number = 25,
  anon_sym_true = 26,
  anon_sym_false = 27,
  anon_sym_LBRACK_LBRACK = 28,
  anon_sym_RBRACK_RBRACK = 29,
  sym_link_text = 30,
  sym_source_file = 31,
  sym_passage = 32,
  sym_passage_header = 33,
  sym_tags = 34,
  sym_tag_list = 35,
  sym_metadata = 36,
  sym_passage_content = 37,
  sym_text = 38,
  sym_macro = 39,
  sym_macro_arg = 40,
  sym_string = 41,
  sym_attribute = 42,
  sym_boolean = 43,
  sym_link = 44,
  aux_sym_source_file_repeat1 = 45,
  aux_sym_tag_list_repeat1 = 46,
  aux_sym_passage_content_repeat1 = 47,
  aux_sym_macro_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON_COLON] = "::",
  [sym_passage_name] = "passage_name",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [aux_sym_tag_list_token1] = "tag_list_token1",
  [sym_tag] = "tag",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_json_metadata] = "json_metadata",
  [aux_sym_text_token1] = "text_token1",
  [anon_sym_LT] = "<",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [sym_macro_name] = "macro_name",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [aux_sym_macro_arg_token1] = "macro_arg_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token2] = "string_token2",
  [sym_variable] = "variable",
  [sym_attribute_name] = "attribute_name",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_LBRACK_LBRACK] = "[[",
  [anon_sym_RBRACK_RBRACK] = "]]",
  [sym_link_text] = "link_text",
  [sym_source_file] = "source_file",
  [sym_passage] = "passage",
  [sym_passage_header] = "passage_header",
  [sym_tags] = "tags",
  [sym_tag_list] = "tag_list",
  [sym_metadata] = "metadata",
  [sym_passage_content] = "passage_content",
  [sym_text] = "text",
  [sym_macro] = "macro",
  [sym_macro_arg] = "macro_arg",
  [sym_string] = "string",
  [sym_attribute] = "attribute",
  [sym_boolean] = "boolean",
  [sym_link] = "link",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tag_list_repeat1] = "tag_list_repeat1",
  [aux_sym_passage_content_repeat1] = "passage_content_repeat1",
  [aux_sym_macro_repeat1] = "macro_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [sym_passage_name] = sym_passage_name,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [aux_sym_tag_list_token1] = aux_sym_tag_list_token1,
  [sym_tag] = sym_tag,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_json_metadata] = sym_json_metadata,
  [aux_sym_text_token1] = aux_sym_text_token1,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [sym_macro_name] = sym_macro_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_macro_arg_token1] = aux_sym_macro_arg_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_variable] = sym_variable,
  [sym_attribute_name] = sym_attribute_name,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_LBRACK_LBRACK] = anon_sym_LBRACK_LBRACK,
  [anon_sym_RBRACK_RBRACK] = anon_sym_RBRACK_RBRACK,
  [sym_link_text] = sym_link_text,
  [sym_source_file] = sym_source_file,
  [sym_passage] = sym_passage,
  [sym_passage_header] = sym_passage_header,
  [sym_tags] = sym_tags,
  [sym_tag_list] = sym_tag_list,
  [sym_metadata] = sym_metadata,
  [sym_passage_content] = sym_passage_content,
  [sym_text] = sym_text,
  [sym_macro] = sym_macro,
  [sym_macro_arg] = sym_macro_arg,
  [sym_string] = sym_string,
  [sym_attribute] = sym_attribute,
  [sym_boolean] = sym_boolean,
  [sym_link] = sym_link,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tag_list_repeat1] = aux_sym_tag_list_repeat1,
  [aux_sym_passage_content_repeat1] = aux_sym_passage_content_repeat1,
  [aux_sym_macro_repeat1] = aux_sym_macro_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_passage_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tag_list_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_json_metadata] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_macro_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_macro_arg_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_link_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_passage] = {
    .visible = true,
    .named = true,
  },
  [sym_passage_header] = {
    .visible = true,
    .named = true,
  },
  [sym_tags] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_list] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata] = {
    .visible = true,
    .named = true,
  },
  [sym_passage_content] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_passage_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
};

static const TSCharacterRange aux_sym_macro_arg_token1_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '&'}, {'(', '+'}, {'-', '9'}, {';', ';'}, {'?', 'Z'},
  {'\\', '\\'}, {'^', 'z'}, {'|', '|'}, {'~', 0x17e}, {0x180, 0x2129}, {0x212b, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 53,
        '$', 50,
        '\'', 56,
        ',', 39,
        ':', 40,
        '<', 34,
        '=', 38,
        '>', 4,
        '[', 19,
        ']', 20,
        'f', 42,
        't', 46,
        '{', 28,
        '}', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(52);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != '{' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(17);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 53,
        '$', 50,
        '\'', 56,
        ',', 39,
        ':', 40,
        '=', 38,
        '>', 4,
        '[', 18,
        ']', 20,
        'f', 42,
        't', 46,
        '{', 28,
        '}', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(52);
      END_STATE();
    case 3:
      if (lookahead == ':') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(36);
      END_STATE();
    case 5:
      if (lookahead == ']') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == ']') ADVANCE(62);
      END_STATE();
    case 7:
      if (lookahead == ']') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 8:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(31);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 10:
      if (eof) ADVANCE(13);
      if (lookahead == ':') ADVANCE(3);
      if (lookahead == ']') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 11:
      if (eof) ADVANCE(13);
      if (lookahead == ':') ADVANCE(32);
      if (lookahead == '<') ADVANCE(34);
      if (lookahead == '[') ADVANCE(19);
      if (lookahead == '{') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == ':') ADVANCE(32);
      if (lookahead == '<') ADVANCE(34);
      if (lookahead == '[') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '[' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_passage_name);
      if (lookahead == '\n') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != '{' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_passage_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '[' &&
          lookahead != '{' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '[') ADVANCE(61);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_tag_list_token1);
      if (lookahead == ']') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_tag_list_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_tag_list_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '[' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_tag_list_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_tag_list_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(58);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_tag_list_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(31);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '[' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_json_metadata);
      if (lookahead != 0 &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '[' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '[' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '<') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_macro_name);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == '.') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(52);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == 'a') ADVANCE(45);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(52);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == 'e') ADVANCE(59);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(52);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == 'e') ADVANCE(60);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(52);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == 'l') ADVANCE(47);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(52);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == 'r') ADVANCE(48);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(52);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == 's') ADVANCE(44);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(52);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == 'u') ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(52);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(52);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(52);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(52);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_link_text);
      if (lookahead == ']') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 11},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 12},
  [18] = {.lex_state = 12},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 12},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 10},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 10},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 10},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 54},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 57},
  [41] = {.lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [aux_sym_tag_list_token1] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_macro_arg_token1] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [sym_attribute_name] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(32),
    [sym_passage] = STATE(23),
    [sym_passage_header] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_COLON_COLON] = ACTIONS(7),
    [aux_sym_tag_list_token1] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(11), 1,
      anon_sym_GT_GT,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_attribute_name,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym_macro_arg,
      aux_sym_macro_repeat1,
    ACTIONS(13), 3,
      aux_sym_macro_arg_token1,
      sym_variable,
      sym_number,
    STATE(6), 3,
      sym_string,
      sym_attribute,
      sym_boolean,
    ACTIONS(9), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_COLON,
  [43] = 10,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(26), 1,
      anon_sym_GT_GT,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(34), 1,
      anon_sym_SQUOTE,
    ACTIONS(37), 1,
      sym_attribute_name,
    ACTIONS(40), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym_macro_arg,
      aux_sym_macro_repeat1,
    ACTIONS(28), 3,
      aux_sym_macro_arg_token1,
      sym_variable,
      sym_number,
    STATE(6), 3,
      sym_string,
      sym_attribute,
      sym_boolean,
    ACTIONS(23), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_COLON,
  [86] = 10,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_attribute_name,
    ACTIONS(43), 1,
      anon_sym_GT_GT,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym_macro_arg,
      aux_sym_macro_repeat1,
    ACTIONS(13), 3,
      aux_sym_macro_arg_token1,
      sym_variable,
      sym_number,
    STATE(6), 3,
      sym_string,
      sym_attribute,
      sym_boolean,
    ACTIONS(9), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_COLON,
  [129] = 3,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(47), 6,
      aux_sym_macro_arg_token1,
      sym_variable,
      sym_attribute_name,
      sym_number,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 10,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_GT_GT,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [153] = 3,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(51), 6,
      aux_sym_macro_arg_token1,
      sym_variable,
      sym_attribute_name,
      sym_number,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(49), 10,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_GT_GT,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [177] = 3,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(55), 6,
      aux_sym_macro_arg_token1,
      sym_variable,
      sym_attribute_name,
      sym_number,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(53), 10,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_GT_GT,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [201] = 3,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(59), 6,
      aux_sym_macro_arg_token1,
      sym_variable,
      sym_attribute_name,
      sym_number,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(57), 10,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_GT_GT,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [225] = 8,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(63), 1,
      anon_sym_COLON_COLON,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(69), 1,
      anon_sym_LT_LT,
    ACTIONS(71), 1,
      anon_sym_LBRACK_LBRACK,
    STATE(28), 1,
      sym_passage_content,
    ACTIONS(65), 3,
      anon_sym_LBRACK,
      aux_sym_text_token1,
      anon_sym_LT,
    STATE(11), 4,
      sym_text,
      sym_macro,
      sym_link,
      aux_sym_passage_content_repeat1,
  [255] = 7,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 1,
      anon_sym_COLON_COLON,
    ACTIONS(80), 1,
      anon_sym_LT_LT,
    ACTIONS(83), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(77), 3,
      anon_sym_LBRACK,
      aux_sym_text_token1,
      anon_sym_LT,
    STATE(10), 4,
      sym_text,
      sym_macro,
      sym_link,
      aux_sym_passage_content_repeat1,
  [282] = 7,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(69), 1,
      anon_sym_LT_LT,
    ACTIONS(71), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(88), 1,
      anon_sym_COLON_COLON,
    ACTIONS(65), 3,
      anon_sym_LBRACK,
      aux_sym_text_token1,
      anon_sym_LT,
    STATE(10), 4,
      sym_text,
      sym_macro,
      sym_link,
      aux_sym_passage_content_repeat1,
  [309] = 7,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(94), 1,
      anon_sym_LBRACK,
    ACTIONS(97), 1,
      anon_sym_LBRACE,
    STATE(13), 1,
      sym_tags,
    STATE(17), 1,
      sym_metadata,
    ACTIONS(90), 3,
      ts_builtin_sym_end,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(92), 3,
      anon_sym_COLON_COLON,
      aux_sym_text_token1,
      anon_sym_LT,
  [335] = 5,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(97), 1,
      anon_sym_LBRACE,
    STATE(18), 1,
      sym_metadata,
    ACTIONS(99), 3,
      ts_builtin_sym_end,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(101), 4,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      aux_sym_text_token1,
      anon_sym_LT,
  [356] = 3,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(103), 3,
      ts_builtin_sym_end,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(105), 5,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_text_token1,
      anon_sym_LT,
  [372] = 3,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(107), 3,
      ts_builtin_sym_end,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(109), 5,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_text_token1,
      anon_sym_LT,
  [388] = 3,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(111), 3,
      ts_builtin_sym_end,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(113), 4,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      aux_sym_text_token1,
      anon_sym_LT,
  [403] = 3,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(99), 3,
      ts_builtin_sym_end,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(101), 4,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      aux_sym_text_token1,
      anon_sym_LT,
  [418] = 3,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(115), 3,
      ts_builtin_sym_end,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(117), 4,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      aux_sym_text_token1,
      anon_sym_LT,
  [433] = 3,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(119), 3,
      ts_builtin_sym_end,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(121), 4,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      aux_sym_text_token1,
      anon_sym_LT,
  [448] = 3,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(123), 3,
      ts_builtin_sym_end,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(125), 4,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      aux_sym_text_token1,
      anon_sym_LT,
  [463] = 3,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(127), 3,
      ts_builtin_sym_end,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(129), 4,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      aux_sym_text_token1,
      anon_sym_LT,
  [478] = 3,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(131), 3,
      ts_builtin_sym_end,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(133), 4,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      aux_sym_text_token1,
      anon_sym_LT,
  [493] = 5,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(7), 1,
      anon_sym_COLON_COLON,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      sym_passage_header,
    STATE(24), 2,
      sym_passage,
      aux_sym_source_file_repeat1,
  [510] = 5,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    ACTIONS(139), 1,
      anon_sym_COLON_COLON,
    STATE(9), 1,
      sym_passage_header,
    STATE(24), 2,
      sym_passage,
      aux_sym_source_file_repeat1,
  [527] = 4,
    ACTIONS(142), 1,
      anon_sym_RBRACK,
    STATE(26), 1,
      aux_sym_tag_list_repeat1,
    STATE(29), 1,
      sym_tag_list,
    ACTIONS(144), 2,
      aux_sym_tag_list_token1,
      sym_tag,
  [541] = 3,
    ACTIONS(146), 1,
      anon_sym_RBRACK,
    STATE(27), 1,
      aux_sym_tag_list_repeat1,
    ACTIONS(148), 2,
      aux_sym_tag_list_token1,
      sym_tag,
  [552] = 3,
    ACTIONS(150), 1,
      anon_sym_RBRACK,
    STATE(27), 1,
      aux_sym_tag_list_repeat1,
    ACTIONS(152), 2,
      aux_sym_tag_list_token1,
      sym_tag,
  [563] = 2,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(155), 2,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
  [571] = 2,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(157), 1,
      anon_sym_RBRACK,
  [578] = 2,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(159), 1,
      anon_sym_RBRACK_RBRACK,
  [585] = 2,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(161), 1,
      anon_sym_RBRACE,
  [592] = 2,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(163), 1,
      ts_builtin_sym_end,
  [599] = 2,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(165), 1,
      sym_link_text,
  [606] = 2,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(167), 1,
      sym_macro_name,
  [613] = 2,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(169), 1,
      aux_sym_string_token1,
  [620] = 2,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(171), 1,
      sym_passage_name,
  [627] = 2,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(173), 1,
      anon_sym_SQUOTE,
  [634] = 2,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(175), 1,
      anon_sym_EQ,
  [641] = 2,
    ACTIONS(3), 1,
      aux_sym_tag_list_token1,
    ACTIONS(173), 1,
      anon_sym_DQUOTE,
  [648] = 2,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(177), 1,
      aux_sym_string_token2,
  [655] = 2,
    ACTIONS(67), 1,
      aux_sym_tag_list_token1,
    ACTIONS(179), 1,
      sym_json_metadata,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 129,
  [SMALL_STATE(6)] = 153,
  [SMALL_STATE(7)] = 177,
  [SMALL_STATE(8)] = 201,
  [SMALL_STATE(9)] = 225,
  [SMALL_STATE(10)] = 255,
  [SMALL_STATE(11)] = 282,
  [SMALL_STATE(12)] = 309,
  [SMALL_STATE(13)] = 335,
  [SMALL_STATE(14)] = 356,
  [SMALL_STATE(15)] = 372,
  [SMALL_STATE(16)] = 388,
  [SMALL_STATE(17)] = 403,
  [SMALL_STATE(18)] = 418,
  [SMALL_STATE(19)] = 433,
  [SMALL_STATE(20)] = 448,
  [SMALL_STATE(21)] = 463,
  [SMALL_STATE(22)] = 478,
  [SMALL_STATE(23)] = 493,
  [SMALL_STATE(24)] = 510,
  [SMALL_STATE(25)] = 527,
  [SMALL_STATE(26)] = 541,
  [SMALL_STATE(27)] = 552,
  [SMALL_STATE(28)] = 563,
  [SMALL_STATE(29)] = 571,
  [SMALL_STATE(30)] = 578,
  [SMALL_STATE(31)] = 585,
  [SMALL_STATE(32)] = 592,
  [SMALL_STATE(33)] = 599,
  [SMALL_STATE(34)] = 606,
  [SMALL_STATE(35)] = 613,
  [SMALL_STATE(36)] = 620,
  [SMALL_STATE(37)] = 627,
  [SMALL_STATE(38)] = 634,
  [SMALL_STATE(39)] = 641,
  [SMALL_STATE(40)] = 648,
  [SMALL_STATE(41)] = 655,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_macro_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_macro_repeat1, 2, 0, 0),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_macro_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_macro_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_arg, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_arg, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_passage, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_passage_content_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_passage_content_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_passage_content_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_passage_content_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_passage_content_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage_content, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_passage_content, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage_header, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_passage_header, 2, 0, 0),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_passage_header, 2, 0, 0), SHIFT(25),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage_header, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_passage_header, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tags, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tags, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tags, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tags, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage_header, 4, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_passage_header, 4, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 4, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 4, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_list, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_list_repeat1, 2, 0, 0),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_list_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [163] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_twee3(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
