/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 51
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_COLON_COLON = 2,
  aux_sym_passage_name_token1 = 3,
  aux_sym_passage_name_token2 = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  aux_sym_tag_list_token1 = 7,
  sym_tag = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  aux_sym_json_metadata_token1 = 11,
  aux_sym_json_metadata_token2 = 12,
  aux_sym_text_token1 = 13,
  anon_sym_COLON = 14,
  anon_sym_LT = 15,
  anon_sym_LT_LT = 16,
  anon_sym_GT_GT = 17,
  sym_macro_name = 18,
  anon_sym_EQ = 19,
  anon_sym_COMMA = 20,
  aux_sym_macro_arg_token1 = 21,
  anon_sym_DQUOTE = 22,
  aux_sym_string_token1 = 23,
  anon_sym_SQUOTE = 24,
  aux_sym_string_token2 = 25,
  sym_variable = 26,
  sym_attribute_name = 27,
  sym_number = 28,
  anon_sym_true = 29,
  anon_sym_false = 30,
  anon_sym_LBRACK_LBRACK = 31,
  anon_sym_RBRACK_RBRACK = 32,
  sym_link_text = 33,
  sym_source_file = 34,
  aux_sym__leading_newlines = 35,
  sym_passage = 36,
  sym_passage_header = 37,
  sym_passage_name = 38,
  sym_tags = 39,
  sym_tag_list = 40,
  sym_metadata = 41,
  sym_json_metadata = 42,
  sym_passage_content = 43,
  sym_text = 44,
  sym_macro = 45,
  sym_macro_arg = 46,
  sym_string = 47,
  sym_attribute = 48,
  sym_boolean = 49,
  sym_link = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_tag_list_repeat1 = 52,
  aux_sym_json_metadata_repeat1 = 53,
  aux_sym_passage_content_repeat1 = 54,
  aux_sym_macro_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_COLON_COLON] = "::",
  [aux_sym_passage_name_token1] = "passage_name_token1",
  [aux_sym_passage_name_token2] = "passage_name_token2",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [aux_sym_tag_list_token1] = "tag_list_token1",
  [sym_tag] = "tag",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym_json_metadata_token1] = "json_metadata_token1",
  [aux_sym_json_metadata_token2] = "json_metadata_token2",
  [aux_sym_text_token1] = "text_token1",
  [anon_sym_COLON] = ":",
  [anon_sym_LT] = "<",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [sym_macro_name] = "macro_name",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [aux_sym_macro_arg_token1] = "macro_arg_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token2] = "string_token2",
  [sym_variable] = "variable",
  [sym_attribute_name] = "attribute_name",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_LBRACK_LBRACK] = "[[",
  [anon_sym_RBRACK_RBRACK] = "]]",
  [sym_link_text] = "link_text",
  [sym_source_file] = "source_file",
  [aux_sym__leading_newlines] = "_leading_newlines",
  [sym_passage] = "passage",
  [sym_passage_header] = "passage_header",
  [sym_passage_name] = "passage_name",
  [sym_tags] = "tags",
  [sym_tag_list] = "tag_list",
  [sym_metadata] = "metadata",
  [sym_json_metadata] = "json_metadata",
  [sym_passage_content] = "passage_content",
  [sym_text] = "text",
  [sym_macro] = "macro",
  [sym_macro_arg] = "macro_arg",
  [sym_string] = "string",
  [sym_attribute] = "attribute",
  [sym_boolean] = "boolean",
  [sym_link] = "link",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tag_list_repeat1] = "tag_list_repeat1",
  [aux_sym_json_metadata_repeat1] = "json_metadata_repeat1",
  [aux_sym_passage_content_repeat1] = "passage_content_repeat1",
  [aux_sym_macro_repeat1] = "macro_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [aux_sym_passage_name_token1] = aux_sym_passage_name_token1,
  [aux_sym_passage_name_token2] = aux_sym_passage_name_token2,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [aux_sym_tag_list_token1] = aux_sym_tag_list_token1,
  [sym_tag] = sym_tag,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_json_metadata_token1] = aux_sym_json_metadata_token1,
  [aux_sym_json_metadata_token2] = aux_sym_json_metadata_token2,
  [aux_sym_text_token1] = aux_sym_text_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [sym_macro_name] = sym_macro_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_macro_arg_token1] = aux_sym_macro_arg_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_variable] = sym_variable,
  [sym_attribute_name] = sym_attribute_name,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_LBRACK_LBRACK] = anon_sym_LBRACK_LBRACK,
  [anon_sym_RBRACK_RBRACK] = anon_sym_RBRACK_RBRACK,
  [sym_link_text] = sym_link_text,
  [sym_source_file] = sym_source_file,
  [aux_sym__leading_newlines] = aux_sym__leading_newlines,
  [sym_passage] = sym_passage,
  [sym_passage_header] = sym_passage_header,
  [sym_passage_name] = sym_passage_name,
  [sym_tags] = sym_tags,
  [sym_tag_list] = sym_tag_list,
  [sym_metadata] = sym_metadata,
  [sym_json_metadata] = sym_json_metadata,
  [sym_passage_content] = sym_passage_content,
  [sym_text] = sym_text,
  [sym_macro] = sym_macro,
  [sym_macro_arg] = sym_macro_arg,
  [sym_string] = sym_string,
  [sym_attribute] = sym_attribute,
  [sym_boolean] = sym_boolean,
  [sym_link] = sym_link,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tag_list_repeat1] = aux_sym_tag_list_repeat1,
  [aux_sym_json_metadata_repeat1] = aux_sym_json_metadata_repeat1,
  [aux_sym_passage_content_repeat1] = aux_sym_passage_content_repeat1,
  [aux_sym_macro_repeat1] = aux_sym_macro_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_passage_name_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_passage_name_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tag_list_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_json_metadata_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_json_metadata_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_macro_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_macro_arg_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_link_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__leading_newlines] = {
    .visible = false,
    .named = false,
  },
  [sym_passage] = {
    .visible = true,
    .named = true,
  },
  [sym_passage_header] = {
    .visible = true,
    .named = true,
  },
  [sym_passage_name] = {
    .visible = true,
    .named = true,
  },
  [sym_tags] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_list] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata] = {
    .visible = true,
    .named = true,
  },
  [sym_json_metadata] = {
    .visible = true,
    .named = true,
  },
  [sym_passage_content] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_json_metadata_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_passage_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
};

static const TSCharacterRange aux_sym_macro_arg_token1_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '&'}, {'(', '+'}, {'-', '9'}, {';', ';'}, {'?', 'Z'},
  {'\\', '\\'}, {'^', 'z'}, {'|', '|'}, {'~', 0x17e}, {0x180, 0x2129}, {0x212b, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '\n', 16,
        '"', 54,
        '$', 51,
        '\'', 57,
        ',', 41,
        ':', 35,
        '<', 36,
        '=', 40,
        '>', 4,
        '[', 22,
        ']', 23,
        'f', 43,
        't', 47,
        '{', 27,
        '}', 28,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(53);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 54,
        '$', 51,
        '\'', 57,
        ',', 41,
        ':', 34,
        '=', 40,
        '>', 4,
        '[', 21,
        ']', 23,
        'f', 43,
        't', 47,
        '{', 27,
        '}', 28,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(53);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '}') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(31);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(38);
      END_STATE();
    case 5:
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == ']') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(24);
      if (('\n' <= lookahead && lookahead <= '\f')) ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(26);
      END_STATE();
    case 6:
      if (lookahead == '\\') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '[' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == ']') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 8:
      if (lookahead == ']') ADVANCE(63);
      END_STATE();
    case 9:
      if (lookahead == ']') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(65);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(3);
      END_STATE();
    case 12:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(65);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '\n', 16,
        ':', 35,
        '<', 36,
        '[', 22,
        '{', 27,
        '\t', 32,
        '\r', 32,
        ' ', 32,
      );
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_passage_name_token1);
      if (lookahead == '\\') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '[' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_passage_name_token1);
      if (lookahead == '\\') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '[' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_passage_name_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '[') ADVANCE(62);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_tag_list_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(24);
      if (('\n' <= lookahead && lookahead <= '\f')) ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_tag_list_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '\\' &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_json_metadata_token1);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_json_metadata_token2);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_json_metadata_token2);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '}' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead)) ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == ',' ||
          lookahead == '=' ||
          lookahead == '>' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ':' &&
          lookahead != '<' &&
          lookahead != '[' &&
          lookahead != '{' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(17);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '<') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_macro_name);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == '.') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(53);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == 'a') ADVANCE(46);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(53);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == 'e') ADVANCE(60);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(53);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == 'e') ADVANCE(61);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(53);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == 'l') ADVANCE(48);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(53);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == 'r') ADVANCE(49);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(53);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == 's') ADVANCE(45);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(53);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == 'u') ADVANCE(44);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(53);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(53);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(53);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_macro_arg_token1);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(53);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      if ((!eof && set_contains(aux_sym_macro_arg_token1_character_set_1, 14, lookahead))) ADVANCE(53);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_link_text);
      if (lookahead == ']') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_link_text);
      if (lookahead == ']') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(65);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 14},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 14},
  [12] = {.lex_state = 14},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 14},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 14},
  [17] = {.lex_state = 14},
  [18] = {.lex_state = 14},
  [19] = {.lex_state = 14},
  [20] = {.lex_state = 14},
  [21] = {.lex_state = 14},
  [22] = {.lex_state = 14},
  [23] = {.lex_state = 14},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 20},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 20},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 9},
  [47] = {.lex_state = 20},
  [48] = {.lex_state = 55},
  [49] = {.lex_state = 58},
  [50] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_macro_arg_token1] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [sym_attribute_name] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(38),
    [aux_sym__leading_newlines] = STATE(24),
    [sym_passage] = STATE(27),
    [sym_passage_header] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(27),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_COLON_COLON] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(11), 1,
      anon_sym_GT_GT,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_attribute_name,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym_macro_arg,
      aux_sym_macro_repeat1,
    ACTIONS(13), 3,
      aux_sym_macro_arg_token1,
      sym_variable,
      sym_number,
    STATE(7), 3,
      sym_string,
      sym_attribute,
      sym_boolean,
    ACTIONS(9), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_COMMA,
  [40] = 9,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_attribute_name,
    ACTIONS(23), 1,
      anon_sym_GT_GT,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_macro_arg,
      aux_sym_macro_repeat1,
    ACTIONS(13), 3,
      aux_sym_macro_arg_token1,
      sym_variable,
      sym_number,
    STATE(7), 3,
      sym_string,
      sym_attribute,
      sym_boolean,
    ACTIONS(9), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_COMMA,
  [80] = 9,
    ACTIONS(28), 1,
      anon_sym_GT_GT,
    ACTIONS(33), 1,
      anon_sym_DQUOTE,
    ACTIONS(36), 1,
      anon_sym_SQUOTE,
    ACTIONS(39), 1,
      sym_attribute_name,
    ACTIONS(42), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_macro_arg,
      aux_sym_macro_repeat1,
    ACTIONS(30), 3,
      aux_sym_macro_arg_token1,
      sym_variable,
      sym_number,
    STATE(7), 3,
      sym_string,
      sym_attribute,
      sym_boolean,
    ACTIONS(25), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_COMMA,
  [120] = 2,
    ACTIONS(47), 6,
      aux_sym_macro_arg_token1,
      sym_variable,
      sym_attribute_name,
      sym_number,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 10,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_GT_GT,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [141] = 2,
    ACTIONS(51), 6,
      aux_sym_macro_arg_token1,
      sym_variable,
      sym_attribute_name,
      sym_number,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(49), 10,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_GT_GT,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [162] = 2,
    ACTIONS(55), 6,
      aux_sym_macro_arg_token1,
      sym_variable,
      sym_attribute_name,
      sym_number,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(53), 10,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_GT_GT,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [183] = 2,
    ACTIONS(59), 6,
      aux_sym_macro_arg_token1,
      sym_variable,
      sym_attribute_name,
      sym_number,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(57), 10,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_GT_GT,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [204] = 8,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 1,
      anon_sym_COLON_COLON,
    ACTIONS(67), 1,
      aux_sym_text_token1,
    ACTIONS(69), 1,
      anon_sym_LT_LT,
    ACTIONS(71), 1,
      anon_sym_LBRACK_LBRACK,
    STATE(36), 1,
      sym_passage_content,
    STATE(11), 4,
      sym_text,
      sym_macro,
      sym_link,
      aux_sym_passage_content_repeat1,
    ACTIONS(63), 5,
      anon_sym_LF,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_LT,
  [236] = 7,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 1,
      anon_sym_COLON_COLON,
    ACTIONS(80), 1,
      aux_sym_text_token1,
    ACTIONS(83), 1,
      anon_sym_LT_LT,
    ACTIONS(86), 1,
      anon_sym_LBRACK_LBRACK,
    STATE(10), 4,
      sym_text,
      sym_macro,
      sym_link,
      aux_sym_passage_content_repeat1,
    ACTIONS(75), 5,
      anon_sym_LF,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_LT,
  [265] = 7,
    ACTIONS(67), 1,
      aux_sym_text_token1,
    ACTIONS(69), 1,
      anon_sym_LT_LT,
    ACTIONS(71), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    ACTIONS(91), 1,
      anon_sym_COLON_COLON,
    STATE(10), 4,
      sym_text,
      sym_macro,
      sym_link,
      aux_sym_passage_content_repeat1,
    ACTIONS(63), 5,
      anon_sym_LF,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_LT,
  [294] = 6,
    ACTIONS(97), 1,
      anon_sym_LBRACK,
    ACTIONS(100), 1,
      anon_sym_LBRACE,
    STATE(13), 1,
      sym_tags,
    STATE(15), 1,
      sym_metadata,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(95), 6,
      anon_sym_LF,
      anon_sym_COLON_COLON,
      anon_sym_COLON,
      anon_sym_LT,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
  [319] = 4,
    ACTIONS(107), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      sym_metadata,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(105), 7,
      anon_sym_LF,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      anon_sym_COLON,
      anon_sym_LT,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
  [339] = 2,
    ACTIONS(110), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(112), 8,
      anon_sym_LF,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_LT,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
  [354] = 2,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(105), 8,
      anon_sym_LF,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_LT,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
  [369] = 2,
    ACTIONS(114), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(116), 8,
      anon_sym_LF,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_LT,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
  [384] = 2,
    ACTIONS(118), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(120), 8,
      anon_sym_LF,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_LT,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
  [399] = 2,
    ACTIONS(122), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(124), 8,
      anon_sym_LF,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_LT,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
  [414] = 2,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(128), 8,
      anon_sym_LF,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_LT,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
  [429] = 2,
    ACTIONS(130), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(132), 8,
      anon_sym_LF,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_LT,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
  [444] = 2,
    ACTIONS(134), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(136), 8,
      anon_sym_LF,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_LT,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
  [459] = 2,
    ACTIONS(138), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(140), 8,
      anon_sym_LF,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_LT,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
  [474] = 2,
    ACTIONS(142), 2,
      ts_builtin_sym_end,
      aux_sym_text_token1,
    ACTIONS(144), 8,
      anon_sym_LF,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_LT,
      anon_sym_LT_LT,
      anon_sym_LBRACK_LBRACK,
  [489] = 6,
    ACTIONS(7), 1,
      anon_sym_COLON_COLON,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
    ACTIONS(148), 1,
      anon_sym_LF,
    STATE(9), 1,
      sym_passage_header,
    STATE(33), 1,
      aux_sym__leading_newlines,
    STATE(28), 2,
      sym_passage,
      aux_sym_source_file_repeat1,
  [509] = 4,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    ACTIONS(152), 1,
      anon_sym_COLON_COLON,
    STATE(9), 1,
      sym_passage_header,
    STATE(25), 2,
      sym_passage,
      aux_sym_source_file_repeat1,
  [523] = 5,
    ACTIONS(155), 1,
      anon_sym_RBRACK,
    ACTIONS(157), 1,
      aux_sym_tag_list_token1,
    ACTIONS(159), 1,
      sym_tag,
    STATE(29), 1,
      aux_sym_tag_list_repeat1,
    STATE(37), 1,
      sym_tag_list,
  [539] = 4,
    ACTIONS(7), 1,
      anon_sym_COLON_COLON,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      sym_passage_header,
    STATE(25), 2,
      sym_passage,
      aux_sym_source_file_repeat1,
  [553] = 4,
    ACTIONS(7), 1,
      anon_sym_COLON_COLON,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      sym_passage_header,
    STATE(25), 2,
      sym_passage,
      aux_sym_source_file_repeat1,
  [567] = 4,
    ACTIONS(163), 1,
      anon_sym_RBRACK,
    ACTIONS(165), 1,
      aux_sym_tag_list_token1,
    ACTIONS(167), 1,
      sym_tag,
    STATE(34), 1,
      aux_sym_tag_list_repeat1,
  [580] = 4,
    ACTIONS(169), 1,
      anon_sym_RBRACE,
    ACTIONS(171), 1,
      aux_sym_json_metadata_token1,
    ACTIONS(173), 1,
      aux_sym_json_metadata_token2,
    STATE(32), 1,
      aux_sym_json_metadata_repeat1,
  [593] = 4,
    ACTIONS(175), 1,
      aux_sym_json_metadata_token1,
    ACTIONS(177), 1,
      aux_sym_json_metadata_token2,
    STATE(30), 1,
      aux_sym_json_metadata_repeat1,
    STATE(39), 1,
      sym_json_metadata,
  [606] = 4,
    ACTIONS(179), 1,
      anon_sym_RBRACE,
    ACTIONS(181), 1,
      aux_sym_json_metadata_token1,
    ACTIONS(184), 1,
      aux_sym_json_metadata_token2,
    STATE(32), 1,
      aux_sym_json_metadata_repeat1,
  [619] = 3,
    ACTIONS(189), 1,
      anon_sym_LF,
    STATE(33), 1,
      aux_sym__leading_newlines,
    ACTIONS(187), 2,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
  [630] = 4,
    ACTIONS(192), 1,
      anon_sym_RBRACK,
    ACTIONS(194), 1,
      aux_sym_tag_list_token1,
    ACTIONS(197), 1,
      sym_tag,
    STATE(34), 1,
      aux_sym_tag_list_repeat1,
  [643] = 2,
    ACTIONS(200), 1,
      aux_sym_passage_name_token1,
    STATE(12), 1,
      sym_passage_name,
  [650] = 1,
    ACTIONS(202), 2,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
  [655] = 1,
    ACTIONS(204), 1,
      anon_sym_RBRACK,
  [659] = 1,
    ACTIONS(206), 1,
      ts_builtin_sym_end,
  [663] = 1,
    ACTIONS(208), 1,
      anon_sym_RBRACE,
  [667] = 1,
    ACTIONS(210), 1,
      aux_sym_passage_name_token2,
  [671] = 1,
    ACTIONS(212), 1,
      anon_sym_RBRACK_RBRACK,
  [675] = 1,
    ACTIONS(214), 1,
      aux_sym_passage_name_token2,
  [679] = 1,
    ACTIONS(216), 1,
      sym_macro_name,
  [683] = 1,
    ACTIONS(218), 1,
      anon_sym_DQUOTE,
  [687] = 1,
    ACTIONS(218), 1,
      anon_sym_SQUOTE,
  [691] = 1,
    ACTIONS(220), 1,
      sym_link_text,
  [695] = 1,
    ACTIONS(222), 1,
      aux_sym_passage_name_token2,
  [699] = 1,
    ACTIONS(224), 1,
      aux_sym_string_token1,
  [703] = 1,
    ACTIONS(226), 1,
      aux_sym_string_token2,
  [707] = 1,
    ACTIONS(228), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 120,
  [SMALL_STATE(6)] = 141,
  [SMALL_STATE(7)] = 162,
  [SMALL_STATE(8)] = 183,
  [SMALL_STATE(9)] = 204,
  [SMALL_STATE(10)] = 236,
  [SMALL_STATE(11)] = 265,
  [SMALL_STATE(12)] = 294,
  [SMALL_STATE(13)] = 319,
  [SMALL_STATE(14)] = 339,
  [SMALL_STATE(15)] = 354,
  [SMALL_STATE(16)] = 369,
  [SMALL_STATE(17)] = 384,
  [SMALL_STATE(18)] = 399,
  [SMALL_STATE(19)] = 414,
  [SMALL_STATE(20)] = 429,
  [SMALL_STATE(21)] = 444,
  [SMALL_STATE(22)] = 459,
  [SMALL_STATE(23)] = 474,
  [SMALL_STATE(24)] = 489,
  [SMALL_STATE(25)] = 509,
  [SMALL_STATE(26)] = 523,
  [SMALL_STATE(27)] = 539,
  [SMALL_STATE(28)] = 553,
  [SMALL_STATE(29)] = 567,
  [SMALL_STATE(30)] = 580,
  [SMALL_STATE(31)] = 593,
  [SMALL_STATE(32)] = 606,
  [SMALL_STATE(33)] = 619,
  [SMALL_STATE(34)] = 630,
  [SMALL_STATE(35)] = 643,
  [SMALL_STATE(36)] = 650,
  [SMALL_STATE(37)] = 655,
  [SMALL_STATE(38)] = 659,
  [SMALL_STATE(39)] = 663,
  [SMALL_STATE(40)] = 667,
  [SMALL_STATE(41)] = 671,
  [SMALL_STATE(42)] = 675,
  [SMALL_STATE(43)] = 679,
  [SMALL_STATE(44)] = 683,
  [SMALL_STATE(45)] = 687,
  [SMALL_STATE(46)] = 691,
  [SMALL_STATE(47)] = 695,
  [SMALL_STATE(48)] = 699,
  [SMALL_STATE(49)] = 703,
  [SMALL_STATE(50)] = 707,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_macro_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_macro_repeat1, 2, 0, 0),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_macro_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_macro_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_arg, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_arg, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_passage, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_passage_content_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_passage_content_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_passage_content_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_passage_content_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_passage_content_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_passage_content_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage_content, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_passage_content, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage_header, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_passage_header, 2, 0, 0),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_passage_header, 2, 0, 0), SHIFT(26),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_passage_header, 2, 0, 0), SHIFT(31),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage_header, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_passage_header, 3, 0, 0),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_passage_header, 3, 0, 0), SHIFT(31),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage_name, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_passage_name, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage_header, 4, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_passage_header, 4, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tags, 3, 1, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tags, 3, 1, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 3, 1, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata, 3, 1, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tags, 4, 1, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tags, 4, 1, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 4, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 4, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_list, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_metadata, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_json_metadata_repeat1, 2, 0, 0),
  [181] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_json_metadata_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_json_metadata_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__leading_newlines, 2, 0, 0),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__leading_newlines, 2, 0, 0), SHIFT_REPEAT(33),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_list_repeat1, 2, 0, 0),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_list_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [197] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_list_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage, 2, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [206] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_twee3(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
